### ISSUE TITLE
Add an initial state in httpScript

### ISSUE THREAD

**Issue by brunodavi** [brunodavi/http-scripts#6]
Adds the `initialState` parameter when executing a request

**Example**
```js
httpScript(
  'g :1234/user/$user.id',
  request,
  { user: { id: 1 } } // < Initial State
)
```

**Comment by sailanka02** [comment]
Do you want to httpScript to be overloaded with another method including the initialState parameter or just add the initial state parameter to the existing method?

**Comment by brunodavi** [comment]
The second option something like:
```js
httpScript(script, httpRequest, state = {})
```

**Comment by brunodavi** [comment]
Completed
