### ISSUE TITLE
Testing case insensitive methods

### ISSUE THREAD

**Issue by brunodavi** [brunodavi/http-scripts#9]
Implement some tests that evaluate whether the methods are case insensitive for each method

Available in this file:

https://github.com/brunodavi/http-script/blob/7b61fee520c55796b3148eafb0d6bf20a1522510/tests/parceHttpScript.test.js#L5-L12

**Comment by sailanka02** [comment]
Let me know if I did the test cases right for this and I can continue to test the rest of the methods

**Comment by brunodavi** [comment]
Solved
